### ISSUE TITLE
footer images all have same 'id'

### ISSUE THREAD

**Issue by danielfdickinson** [bowman2001/hugo-mod-image#6]
Using the same type of footer configuration as you have with perplexdoc, I am getting warnings that 'id' is being duplicated for the footer images. I have verified that it is the Markdown images in the footer columns that are all getting id `1`.

E.g.

```html
<h2>Theme</h2>
  <figure class="fig fig--w-text" id="fig-1"><a aria-label="Perplex logo" class="img__frame img__frame--bg-light img__frame--box-shadow img__frame--pad-half" href="https://github.com/bowman2001/perplex">
```

and

```html
<h2>Content</h2>
  <figure class="fig fig--w-tiny" id="fig-1">
    <a aria-label="Creative Commons 4.0 logo" class="img__frame img__frame--bg-light img__frame--box-shadow img__frame--pad-half" href="https://creativecommons.org/licenses/by-sa/4.0/" style="display: flex; justify-content: center; align-items: center">
```

This appears to be happening here:

https://github.com/bowman2001/hugo-mod-image/blob/main/layouts/partials/mod-img/func/params/img-hook.html

I don't see where the ordinal gets set via markdown hook before this code.

**Comment by bowman2001** [comment]
Yes, thanks, the default behavior of the render hook for pages leads to this problem. The footer is composed as a list of many small pages. Because this is a clear exception, I would suggest solving this problem by using explicit IDs for the few images in the footer and to avoid duplicate ones manually.

**Comment by bowman2001** [comment]
Unfortunately, this solution does currently not work, and this is clearly a bug I’ll need to fix. An extra parameter `id` is not properly processed.
